/* Config.c generated by valac 0.28.1, the Vala compiler
 * generated from Config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define CONSTANTS_DATADIR "/usr/share"
#define CONSTANTS_PKGDATADIR "/usr/share/focusapp"
#define CONSTANTS_GETTEXT_PACKAGE "focusapp"
#define CONSTANTS_RELEASE_NAME "focusapp"
#define CONSTANTS_VERSION "1.0.0"



