/* Focus.c generated by valac 0.28.0, the Vala compiler
 * generated from Focus.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <stdio.h>


#define TYPE_FOCUS_APP (focus_app_get_type ())
#define FOCUS_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FOCUS_APP, FocusApp))
#define FOCUS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_FOCUS_APP, FocusAppClass))
#define IS_FOCUS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FOCUS_APP))
#define IS_FOCUS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_FOCUS_APP))
#define FOCUS_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FOCUS_APP, FocusAppClass))

typedef struct _FocusApp FocusApp;
typedef struct _FocusAppClass FocusAppClass;
typedef struct _FocusAppPrivate FocusAppPrivate;
typedef struct _Block1Data Block1Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _FocusApp {
	GtkWindow parent_instance;
	FocusAppPrivate * priv;
};

struct _FocusAppClass {
	GtkWindowClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	FocusApp* self;
	GtkBox* box;
	GtkEntry* entry;
	GtkLabel* _result_;
};


static gpointer focus_app_parent_class = NULL;

GType focus_app_get_type (void) G_GNUC_CONST;
enum  {
	FOCUS_APP_DUMMY_PROPERTY
};
FocusApp* focus_app_new (void);
FocusApp* focus_app_construct (GType object_type);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void __lambda4_ (Block1Data* _data1_);
static void ___lambda4__gtk_entry_activate (GtkEntry* _sender, gpointer self);
gint _vala_main (gchar** args, int args_length1);


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		FocusApp* self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->_result_);
		_g_object_unref0 (_data1_->entry);
		_g_object_unref0 (_data1_->box);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static void __lambda4_ (Block1Data* _data1_) {
	FocusApp* self;
	const gchar* _tmp0_ = NULL;
	self = _data1_->self;
	_tmp0_ = gtk_entry_get_text (_data1_->entry);
	gtk_label_set_label (_data1_->_result_, _tmp0_);
	gtk_entry_set_text (_data1_->entry, "");
	gtk_box_pack_start (_data1_->box, (GtkWidget*) _data1_->_result_, TRUE, TRUE, (guint) 0);
}


static void ___lambda4__gtk_entry_activate (GtkEntry* _sender, gpointer self) {
	__lambda4_ (self);
}


FocusApp* focus_app_construct (GType object_type) {
	FocusApp * self = NULL;
	Block1Data* _data1_;
	static const char LOCAL_DIR[] = "/usr/local/share/focus/";
	GtkSettings* _tmp0_ = NULL;
	gchar* css_file = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GtkCssProvider* provider = NULL;
	GtkCssProvider* _tmp3_ = NULL;
	GtkBox* _tmp8_ = NULL;
	GtkLabel* label = NULL;
	GtkLabel* _tmp9_ = NULL;
	GtkEntry* _tmp10_ = NULL;
	GtkLabel* _tmp11_ = NULL;
	GtkListBox* listBox = NULL;
	GtkListBox* _tmp12_ = NULL;
	GtkLabel* _tmp13_ = NULL;
	GtkLabel* _tmp14_ = NULL;
	GError * _inner_error_ = NULL;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	self = (FocusApp*) g_object_new (object_type, NULL);
	_data1_->self = g_object_ref (self);
	_tmp0_ = gtk_settings_get_default ();
	g_object_set (_tmp0_, "gtk-application-prefer-dark-theme", TRUE, NULL);
	gtk_window_set_title ((GtkWindow*) self, "Focus");
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 10);
	gtk_window_set_position ((GtkWindow*) self, GTK_WIN_POS_CENTER);
	gtk_window_set_default_size ((GtkWindow*) self, 500, 700);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	_tmp1_ = string_to_string (LOCAL_DIR);
	_tmp2_ = g_strconcat (_tmp1_, " app.css", NULL);
	css_file = _tmp2_;
	_tmp3_ = gtk_css_provider_new ();
	provider = _tmp3_;
	{
		GdkScreen* _tmp4_ = NULL;
		gtk_css_provider_load_from_path (provider, css_file, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp4_ = gdk_screen_get_default ();
		gtk_style_context_add_provider_for_screen (_tmp4_, (GtkStyleProvider*) provider, (guint) GTK_STYLE_PROVIDER_PRIORITY_USER);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = stderr;
		_tmp6_ = e;
		_tmp7_ = _tmp6_->message;
		fprintf (_tmp5_, "Error: %s\n", _tmp7_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (provider);
		_g_free0 (css_file);
		block1_data_unref (_data1_);
		_data1_ = NULL;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp8_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 10);
	g_object_ref_sink (_tmp8_);
	_data1_->box = _tmp8_;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _data1_->box);
	_tmp9_ = (GtkLabel*) gtk_label_new ("<span size='17000'>Focus</span>");
	g_object_ref_sink (_tmp9_);
	label = _tmp9_;
	gtk_label_set_use_markup (label, TRUE);
	gtk_container_add ((GtkContainer*) _data1_->box, (GtkWidget*) label);
	_tmp10_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp10_);
	_data1_->entry = _tmp10_;
	gtk_entry_set_placeholder_text (_data1_->entry, "What are you doing?");
	gtk_entry_set_icon_from_icon_name (_data1_->entry, GTK_ENTRY_ICON_SECONDARY, "media-playback-start");
	gtk_widget_set_tooltip_text ((GtkWidget*) _data1_->entry, "Just Press Enter to insert!");
	gtk_container_add ((GtkContainer*) _data1_->box, (GtkWidget*) _data1_->entry);
	_tmp11_ = (GtkLabel*) gtk_label_new ("Results");
	g_object_ref_sink (_tmp11_);
	_data1_->_result_ = _tmp11_;
	_tmp12_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp12_);
	listBox = _tmp12_;
	g_signal_connect_data (_data1_->entry, "activate", (GCallback) ___lambda4__gtk_entry_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp13_ = (GtkLabel*) gtk_label_new ("Wow");
	g_object_ref_sink (_tmp13_);
	_tmp14_ = _tmp13_;
	gtk_list_box_prepend (listBox, (GtkWidget*) _tmp14_);
	_g_object_unref0 (_tmp14_);
	gtk_box_pack_start (_data1_->box, (GtkWidget*) listBox, TRUE, TRUE, (guint) 0);
	_g_object_unref0 (listBox);
	_g_object_unref0 (label);
	_g_object_unref0 (provider);
	_g_free0 (css_file);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return self;
}


FocusApp* focus_app_new (void) {
	return focus_app_construct (TYPE_FOCUS_APP);
}


static void focus_app_class_init (FocusAppClass * klass) {
	focus_app_parent_class = g_type_class_peek_parent (klass);
}


static void focus_app_instance_init (FocusApp * self) {
}


GType focus_app_get_type (void) {
	static volatile gsize focus_app_type_id__volatile = 0;
	if (g_once_init_enter (&focus_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FocusAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) focus_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FocusApp), 0, (GInstanceInitFunc) focus_app_instance_init, NULL };
		GType focus_app_type_id;
		focus_app_type_id = g_type_register_static (gtk_window_get_type (), "FocusApp", &g_define_type_info, 0);
		g_once_init_leave (&focus_app_type_id__volatile, focus_app_type_id);
	}
	return focus_app_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	FocusApp* win = NULL;
	FocusApp* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = focus_app_new ();
	g_object_ref_sink (_tmp0_);
	win = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) win);
	gtk_main ();
	result = 0;
	_g_object_unref0 (win);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



