/* TaskManager.c generated by valac 0.28.0, the Vala compiler
 * generated from TaskManager.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>


#define TYPE_TASK_MANAGER (task_manager_get_type ())
#define TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TASK_MANAGER, TaskManager))
#define TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TASK_MANAGER, TaskManagerClass))
#define IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TASK_MANAGER))
#define IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TASK_MANAGER))
#define TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TASK_MANAGER, TaskManagerClass))

typedef struct _TaskManager TaskManager;
typedef struct _TaskManagerClass TaskManagerClass;
typedef struct _TaskManagerPrivate TaskManagerPrivate;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
typedef struct _ParamSpecTaskManager ParamSpecTaskManager;

struct _TaskManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TaskManagerPrivate * priv;
	GDateTime* start;
	GDateTime* end;
	gint taskId;
	GDateTime* dateOfTask;
};

struct _TaskManagerClass {
	GTypeClass parent_class;
	void (*finalize) (TaskManager *self);
};

struct _TaskManagerPrivate {
	gboolean _isRunning;
};

struct _ParamSpecTaskManager {
	GParamSpec parent_instance;
};


static gpointer task_manager_parent_class = NULL;

gpointer task_manager_ref (gpointer instance);
void task_manager_unref (gpointer instance);
GParamSpec* param_spec_task_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_task_manager (GValue* value, gpointer v_object);
void value_take_task_manager (GValue* value, gpointer v_object);
gpointer value_get_task_manager (const GValue* value);
GType task_manager_get_type (void) G_GNUC_CONST;
#define TASK_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TASK_MANAGER, TaskManagerPrivate))
enum  {
	TASK_MANAGER_DUMMY_PROPERTY
};
TaskManager* task_manager_new (void);
TaskManager* task_manager_construct (GType object_type);
gboolean task_manager_get_isRunning (TaskManager* self);
static void task_manager_set_isRunning (TaskManager* self, gboolean value);
void task_manager_countTime (TaskManager* self);
static void task_manager_finalize (TaskManager* obj);


TaskManager* task_manager_construct (GType object_type) {
	TaskManager* self = NULL;
	gboolean _tmp0_ = FALSE;
	self = (TaskManager*) g_type_create_instance (object_type);
	_tmp0_ = self->priv->_isRunning;
	if (!_tmp0_) {
		GDateTime* _tmp1_ = NULL;
		gint32 _tmp2_ = 0;
		_tmp1_ = g_date_time_new_now_local ();
		_g_date_time_unref0 (self->start);
		self->start = _tmp1_;
		task_manager_set_isRunning (self, TRUE);
		_tmp2_ = g_random_int_range ((gint32) 0, (gint32) 10000);
		self->taskId = (gint) _tmp2_;
	}
	return self;
}


TaskManager* task_manager_new (void) {
	return task_manager_construct (TYPE_TASK_MANAGER);
}


void task_manager_countTime (TaskManager* self) {
	GDateTime* now = NULL;
	GDateTime* _tmp0_ = NULL;
	gint _result_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_date_time_new_now_local ();
	now = _tmp0_;
	_result_ = 1;
	_g_date_time_unref0 (now);
}


gboolean task_manager_get_isRunning (TaskManager* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_isRunning;
	result = _tmp0_;
	return result;
}


static void task_manager_set_isRunning (TaskManager* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_isRunning = _tmp0_;
}


static void value_task_manager_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_task_manager_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		task_manager_unref (value->data[0].v_pointer);
	}
}


static void value_task_manager_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = task_manager_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_task_manager_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_task_manager_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		TaskManager* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = task_manager_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_task_manager_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	TaskManager** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = task_manager_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_task_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecTaskManager* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_TASK_MANAGER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_task_manager (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TASK_MANAGER), NULL);
	return value->data[0].v_pointer;
}


void value_set_task_manager (GValue* value, gpointer v_object) {
	TaskManager* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TASK_MANAGER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_TASK_MANAGER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		task_manager_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		task_manager_unref (old);
	}
}


void value_take_task_manager (GValue* value, gpointer v_object) {
	TaskManager* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_TASK_MANAGER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_TASK_MANAGER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		task_manager_unref (old);
	}
}


static void task_manager_class_init (TaskManagerClass * klass) {
	task_manager_parent_class = g_type_class_peek_parent (klass);
	((TaskManagerClass *) klass)->finalize = task_manager_finalize;
	g_type_class_add_private (klass, sizeof (TaskManagerPrivate));
}


static void task_manager_instance_init (TaskManager * self) {
	self->priv = TASK_MANAGER_GET_PRIVATE (self);
	self->priv->_isRunning = FALSE;
	self->ref_count = 1;
}


static void task_manager_finalize (TaskManager* obj) {
	TaskManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TASK_MANAGER, TaskManager);
	g_signal_handlers_destroy (self);
	_g_date_time_unref0 (self->start);
	_g_date_time_unref0 (self->end);
	_g_date_time_unref0 (self->dateOfTask);
}


GType task_manager_get_type (void) {
	static volatile gsize task_manager_type_id__volatile = 0;
	if (g_once_init_enter (&task_manager_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_task_manager_init, value_task_manager_free_value, value_task_manager_copy_value, value_task_manager_peek_pointer, "p", value_task_manager_collect_value, "p", value_task_manager_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (TaskManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) task_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TaskManager), 0, (GInstanceInitFunc) task_manager_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType task_manager_type_id;
		task_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "TaskManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&task_manager_type_id__volatile, task_manager_type_id);
	}
	return task_manager_type_id__volatile;
}


gpointer task_manager_ref (gpointer instance) {
	TaskManager* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void task_manager_unref (gpointer instance) {
	TaskManager* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		TASK_MANAGER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



